version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hamza@1234
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - library-network

  api:
    build:
      context: .
      dockerfile: src/LibraryManagementApp.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LibraryManagementDb;User Id=sa;Password=Hamza@1234;TrustServerCertificate=true;
    networks:
      - library-network

volumes:
  sqlserver_data:

networks:
  library-network:
    driver: bridge 